### ISSUE TITLE
Replace tankObject with Player

### ISSUE THREAD

**Issue by lamping7** [rsanchez-wsu/sp15-ceg3120#5]
Mason, "we arent going to use TankObjects, they were placed in the folder initially so that team's code would compile.  There were teams in charge of creating the player class, and game class.  Someone needs to take the usage of TankObjects out and switch the usage to the style of the Player class."

**Comment by lamping7** [comment]
In order to not have to edit much of the server code by team 6, it will be easier to make a change to the player class: remove the point variable, replace with individual int variables. Also the IP and image properties will need to added. Lastly, as was mentioned last class, the lastSeenLocation is not necessary.

**Comment by Matt-Nelson103** [comment]
I added gets and sets to the player class to be able to use the coordinates as an int. I will work on the rest of these changes tonight.

**Comment by lamping7** [comment]
HA... I changed my mind... I didn't think anyone would jump on here that fast.

I just got done implementing the use of "getPlayerLocation().x" etc..

Please don't commit those changes.

**Comment by Matt-Nelson103** [comment]
All I did was add the ability to use it as an int the point functions are
still there.

**Comment by lamping7** [comment]
Sweet. It turned out I had to change his code anyway, so I kept Player as it was.
